[build]
  base = "edtech-social-app"  # Base directory for your Next.js app
  command = "npm run build"
  publish = "build"  # Updated to match the custom distDir in next.config.js

[[plugins]]
  package = "@netlify/plugin-nextjs"