[build]
  base = "edtech-social-app"  # Specify the subdirectory if your Next.js app is not in the root
  command = "npm run build"
  publish = ".next"  # This should be relative to the `base` directory

[[plugins]]
  package = "@netlify/plugin-nextjs"
