"""Add token column to User model

Revision ID: 4323ec61df4c
Revises: 60d4a3fc0ec7
Create Date: 2024-07-06 16:23:40.614205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4323ec61df4c"
down_revision: Union[str, None] = "60d4a3fc0ec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_prisma_migrations")
    op.alter_column("Comment", "video_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("Comment", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("User", sa.Column("token", sa.String(), nullable=True))
    op.alter_column("User", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("User", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("Video", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Video", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("User", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("User", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("User", "token")
    op.alter_column("Comment", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("Comment", "video_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_table(
        "_prisma_migrations",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "checksum", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "migration_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("logs", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "rolled_back_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "applied_steps_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="_prisma_migrations_pkey"),
    )
    # ### end Alembic commands ###
